### ISSUE TITLE
Redirect not working as expected for Tutorial - Part 4 #288

### ISSUE THREAD

**Issue by muhammadmadni-ivl** [redwoodjs/redwoodjs.com#934] opened 2021-12-29 13:12 UTC
Redirect not working as expected for Tutorial - Part 4 #288
https://github.com/redwoodjs/redwoodjs.com/issues/288

same issue as mentioned above
package.json (web)
![image](https://user-images.githubusercontent.com/78340648/147665792-a16f3447-368c-40ab-9b23-08a3efe0a5b3.png)

![image](https://user-images.githubusercontent.com/78340648/147665974-82c24e46-d92c-4aca-9aa4-cf81792d805c.png)

**Comment by dthyresson** [comment] 2021-12-29 15:05
Hi @muhammadmadni-ivl thanks for the note.

I have a question: your issue is about the tutorial, but the example code here is from an app using Auth0 to authenticate.

From your sample code, I would expect that if you are unauthenticated and you attempt to access say the "opportunities" or the "dna" route, your would be sent to the "login" route.

Also, since your "dnaSignatures" route path is "/" root access would bring you to the login page.

BTW - you can also set a private attribute on a Set and not use the <Private> like:

`<Set wrap={DashboardLayout} private unauthenticated="login">`
`<Set wrap={DnaSignaturesLayout} private unauthenticated="login">`

Can you share what happens when to go to a private route and not authenticated?

And can you confirm that there is no access token in storage and `useAuth() hook` doesn't think you are logged in.

Do you get to the "login" page?
 

If not, could you close this issue and report it with reproducible steps in the main Redwood issues repo https://github.com/redwoodjs/redwood/issues for the team to investigate.

Thanks

**Comment by muhammadmadni-ivl** [comment] 2022-01-10 07:56
Sorry for the late reply, I have fixed the issue, its working now, again
sorry for the delay. Thank you so much  David Thyresson.

**Closed** 2022-02-14 23:07 UTC
